# Generated by Django 2.1.5 on 2019-01-30 17:22

from django.db import migrations, models
import django.db.models.deletion
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_auto_20190128_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('path', models.CharField(max_length=255)),
                ('column', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('obj', models.CharField(max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='badge',
            field=models.ImageField(blank=True, null=True, storage=users.storage.OverwriteStorage(), upload_to='pylint_badge'),
        ),
        migrations.AddField(
            model_name='reports',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Repository'),
        ),
    ]
