# Generated by Django 2.1.5 on 2019-01-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionPep8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorPep8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RefactorPep8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarningPep8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='convention',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='error',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='refactor',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Convention',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='Refactor',
        ),
        migrations.DeleteModel(
            name='Warning',
        ),
    ]
